"""
This type stub file was generated by pyright.
"""

import enum
import functools
import json
import logging
import os
import ssl
import time
import typing as t
import warnings
import pandas as pd
import certifi
from http.client import HTTPResponse
from itertools import zip_longest
from urllib.error import HTTPError
from urllib.parse import quote, urlencode
from urllib.request import urlopen

"""PubChemPy: Python Interface for the PubChem Database."""
if t.TYPE_CHECKING:
    ...
_CA_FILE = ...
if not _CA_FILE:
    _CA_FILE = ...
__author__ = ...
__email__ = ...
__version__ = ...
__license__ = ...
__all__ = ["get_compounds", "get_substances", "get_assays", "get_properties", "get_synonyms", "get_cids", "get_sids", "get_aids", "get_all_sources", "download", "request", "get", "get_json", "get_sdf", "Compound", "Substance", "Assay", "Atom", "Bond", "CompoundIdType", "BondType", "CoordinateType", "ProjectCategory", "compounds_to_frame", "substances_to_frame", "API_BASE", "ELEMENTS", "PROPERTY_MAP", "PubChemPyError", "ResponseParseError", "PubChemHTTPError", "BadRequestError", "NotFoundError", "MethodNotAllowedError", "ServerError", "UnimplementedError", "ServerBusyError", "TimeoutError", "PubChemPyDeprecationWarning"]
API_BASE = ...
log = ...
QueryParam = str | int | float | bool | list[str] | None
class CompoundIdType(enum.IntEnum):
    """Compound record type."""
    DEPOSITED = ...
    STANDARDIZED = ...
    COMPONENT = ...
    NEUTRALIZED = ...
    MIXTURE = ...
    TAUTOMER = ...
    IONIZED = ...
    UNKNOWN = ...


class BondType(enum.IntEnum):
    """Bond Type Information."""
    SINGLE = ...
    DOUBLE = ...
    TRIPLE = ...
    QUADRUPLE = ...
    DATIVE = ...
    COMPLEX = ...
    IONIC = ...
    UNKNOWN = ...


class CoordinateType(enum.IntEnum):
    """Coordinate Set Type Distinctions."""
    TWO_D = ...
    THREE_D = ...
    SUBMITTED = ...
    EXPERIMENTAL = ...
    COMPUTED = ...
    STANDARDIZED = ...
    AUGMENTED = ...
    ALIGNED = ...
    COMPACT = ...
    UNITS_ANGSTROMS = ...
    UNITS_NANOMETERS = ...
    UNITS_PIXEL = ...
    UNITS_POINTS = ...
    UNITS_STDBONDS = ...
    UNITS_UNKNOWN = ...


class ProjectCategory(enum.IntEnum):
    """To distinguish projects funded through MLSCN, MLPCN or other."""
    MLSCN = ...
    MLPCN = ...
    MLSCN_AP = ...
    MLPCN_AP = ...
    JOURNAL_ARTICLE = ...
    ASSAY_VENDOR = ...
    LITERATURE_EXTRACTED = ...
    LITERATURE_AUTHOR = ...
    LITERATURE_PUBLISHER = ...
    RNAIGI = ...
    OTHER = ...


ELEMENTS: dict[int, str] = ...
def request(identifier: str | int | list[str | int], namespace: str = ..., domain: str = ..., operation: str | None = ..., output: str = ..., searchtype: str | None = ..., **kwargs: QueryParam) -> HTTPResponse:
    """Construct API request from parameters and return the response.

    Full specification at https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest
    """
    ...

def get(identifier: str | int | list[str | int], namespace: str = ..., domain: str = ..., operation: str | None = ..., output: str = ..., searchtype: str | None = ..., **kwargs: QueryParam) -> bytes:
    """Request wrapper that automatically handles async requests."""
    ...

def get_json(identifier: str | int | list[str | int], namespace: str = ..., domain: str = ..., operation: str | None = ..., searchtype: str | None = ..., **kwargs: QueryParam) -> dict[str, t.Any] | None:
    """Request wrapper that automatically parses JSON response into a python dict.

    This function suppresses NotFoundError and returns None if no results are found.
    """
    ...

def get_sdf(identifier: str | int | list[str | int], namespace: str = ..., domain: str = ..., operation: str | None = ..., searchtype: str | None = ..., **kwargs: QueryParam) -> str | None:
    """Request wrapper that automatically extracts SDF from the response.

    This function suppresses NotFoundError and returns None if no results are found.
    """
    ...

def get_compounds(identifier: str | int | list[str | int], namespace: str = ..., searchtype: str | None = ..., as_dataframe: bool = ..., **kwargs: QueryParam) -> list[Compound] | pd.DataFrame:
    """Retrieve the specified compound records from PubChem.

    Args:
        identifier: The compound identifier to use as a search query.
        namespace: The identifier type, one of cid, name, smiles, sdf, inchi,
            inchikey or formula.
        searchtype: The advanced search type, one of substructure,
            superstructure or similarity.
        as_dataframe: Automatically extract the Compound properties into a pandas
            DataFrame and return that.
        **kwargs: Additional query parameters to pass to the API request.

    Returns:
        List of :class:`~pubchempy.Compound` objects, or a pandas DataFrame if
        ``as_dataframe=True``.
    """
    ...

def get_substances(identifier: str | int | list[str | int], namespace: str = ..., as_dataframe: bool = ..., **kwargs: QueryParam) -> list[Substance] | pd.DataFrame:
    """Retrieve the specified substance records from PubChem.

    Args:
        identifier: The substance identifier to use as a search query.
        namespace: The identifier type, one of sid, name or sourceid/<source name>.
        as_dataframe: Automatically extract the Substance properties into a pandas
            DataFrame and return that.
        **kwargs: Additional query parameters to pass to the API request.

    Returns:
        List of :class:`~pubchempy.Substance` objects, or a pandas DataFrame if
        ``as_dataframe=True``.
    """
    ...

def get_assays(identifier: str | int | list[str | int], namespace: str = ..., **kwargs: QueryParam) -> list[Assay]:
    """Retrieve the specified assay records from PubChem.

    Args:
        identifier: The assay identifier to use as a search query.
        namespace: The identifier type.
        **kwargs: Additional query parameters to pass to the API request.

    Returns:
        List of :class:`~pubchempy.Assay` objects.
    """
    ...

PROPERTY_MAP: dict[str, str] = ...
def get_properties(properties: str | list[str], identifier: str | int | list[str | int], namespace: str = ..., searchtype: str | None = ..., as_dataframe: bool = ..., **kwargs: QueryParam) -> list[dict[str, t.Any]] | pd.DataFrame:
    """Retrieve the specified compound properties from PubChem.

    Args:
        properties: The properties to retrieve.
        identifier: The compound  identifier to use as a search query.
        namespace: The identifier type.
        searchtype: The advanced search type, one of substructure, superstructure
            or similarity.
        as_dataframe: Automatically extract the properties into a pandas DataFrame.
        **kwargs: Additional query parameters to pass to the API request.
    """
    ...

def get_synonyms(identifier: str | int | list[str | int], namespace: str = ..., domain: str = ..., searchtype: str | None = ..., **kwargs: QueryParam) -> list[dict[str, t.Any]]:
    """Retrieve synonyms (alternative names) for the specified records from PubChem.

    Synonyms include systematic names, common names, trade names, registry numbers,
    and other identifiers associated with compounds, substances, or assays.

    Args:
        identifier: The identifier to use as a search query.
        namespace: The identifier type (e.g., cid, name, smiles for compounds).
        domain: The PubChem domain to search (compound or substance).
        searchtype: The advanced search type, one of substructure, superstructure
            or similarity.
        **kwargs: Additional parameters to pass to the request.

    Returns:
        List of dictionaries containing synonym information for each matching record.
        Each dictionary contains the record identifier and a list of synonyms.
    """
    ...

def get_cids(identifier: str | int | list[str | int], namespace: str = ..., domain: str = ..., searchtype: str | None = ..., **kwargs: QueryParam) -> list[int]:
    """Retrieve Compound Identifiers (CIDs) for the specified query from PubChem.

    CIDs are unique numerical identifiers assigned to each standardized compound
    record in the PubChem Compound database. This function is useful for converting
    between different identifier types (names, SMILES, InChI, etc.) and CIDs.

    Args:
        identifier: The identifier to use as a search query.
        namespace: The identifier type (e.g. name, smiles, inchi, formula).
        domain: The PubChem domain to search (compound, substance, or assay).
        searchtype: The advanced search type, one of substructure, superstructure
            or similarity.
        **kwargs: Additional parameters to pass to the request.

    Returns:
        List of CIDs (integers) that match the search criteria. Empty list if no
        matches found.
    """
    ...

def get_sids(identifier: str | int | list[str | int], namespace: str = ..., domain: str = ..., searchtype: str | None = ..., **kwargs: QueryParam) -> list[int]:
    """Retrieve Substance Identifiers (SIDs) for the specified query from PubChem.

    SIDs are unique numerical identifiers assigned to each substance record
    in the PubChem Substance database. This function is useful for finding
    which substance records are associated with a given compound or other identifier.

    Args:
        identifier: The identifier to use as a search query.
        namespace: The identifier type (e.g., cid, name, smiles for compounds).
        domain: The PubChem domain to search (compound, substance, or assay).
        searchtype: The advanced search type, one of substructure, superstructure
            or similarity.
        **kwargs: Additional parameters to pass to the request.

    Returns:
        List of SIDs (integers) that match the search criteria. Empty list if no
        matches found.
    """
    ...

def get_aids(identifier: str | int | list[str | int], namespace: str = ..., domain: str = ..., searchtype: str | None = ..., **kwargs: QueryParam) -> list[int]:
    """Retrieve Assay Identifiers (AIDs) for the specified query from PubChem.

    AIDs are unique numerical identifiers assigned to each biological assay
    record in the PubChem BioAssay database. This function is useful for finding
    which assays have tested a given compound or substance.

    Args:
        identifier: The identifier to use as a search query.
        namespace: The identifier type (e.g., cid, name, smiles).
        domain: The PubChem domain to search (compound, substance, or assay).
        searchtype: The advanced search type, one of substructure, superstructure
            or similarity.
        **kwargs: Additional parameters to pass to the request.

    Returns:
        List of AIDs (integers) that match the search criteria. Empty list if no
        matches found.
    """
    ...

def get_all_sources(domain: str = ...) -> list[str]:
    """Return a list of all current depositors of substances or assays."""
    ...

def download(outformat: str, path: str | os.PathLike, identifier: str | int | list[str | int], namespace: str = ..., domain: str = ..., operation: str | None = ..., searchtype: str | None = ..., overwrite: bool = ..., **kwargs: QueryParam) -> None:
    """Format can be  XML, ASNT/B, JSON, SDF, CSV, PNG, TXT."""
    ...

def memoized_property(fget: t.Callable[[t.Any], t.Any]) -> property:
    """Decorator to create memoized properties.

    Used to cache :class:`~pubchempy.Compound` and :class:`~pubchempy.Substance`
    properties that require an additional request.
    """
    ...

def deprecated(message: str) -> t.Callable[[t.Callable], t.Callable]:
    """Decorator to mark as deprecated and emit a warning when used."""
    ...

class Atom:
    """Class to represent an atom in a :class:`~pubchempy.Compound`."""
    def __init__(self, aid: int, number: int, x: float | None = ..., y: float | None = ..., z: float | None = ..., charge: int = ...) -> None:
        """Initialize with an atom ID, atomic number, coordinates and optional charge.

        Args:
            aid: Atom ID.
            number: Atomic number.
            x: X coordinate.
            y: Y coordinate.
            z: Z coordinate.
            charge: Formal charge on atom.
        """
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    @deprecated("Dictionary style access to Atom attributes is deprecated")
    def __getitem__(self, prop): # -> Any:
        """Allow dict-style access to attributes for backwards compatibility."""
        ...
    
    @deprecated("Dictionary style access to Atom attributes is deprecated")
    def __setitem__(self, prop, val): # -> None:
        """Allow dict-style setting of attributes for backwards compatibility."""
        ...
    
    @deprecated("Dictionary style access to Atom attributes is deprecated")
    def __contains__(self, prop): # -> bool:
        """Allow dict-style checking of attributes for backwards compatibility."""
        ...
    
    @property
    def element(self) -> str:
        """The element symbol for this atom."""
        ...
    
    def to_dict(self) -> dict[str, t.Any]:
        """Return a dictionary containing Atom data."""
        ...
    
    def set_coordinates(self, x: float, y: float, z: float | None = ...) -> None:
        """Set all coordinate dimensions at once."""
        ...
    
    @property
    def coordinate_type(self) -> str:
        """Whether this atom has 2D or 3D coordinates."""
        ...
    


class Bond:
    """Class to represent a bond between two atoms in a :class:`~pubchempy.Compound`."""
    def __init__(self, aid1: int, aid2: int, order: BondType = ..., style: int | None = ...) -> None:
        """Initialize with begin and end atom IDs, bond order and bond style.

        Args:
            aid1: Begin atom ID.
            aid2: End atom ID.
            order: Bond order.
            style: Bond style annotation.
        """
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    @deprecated("Dictionary style access to Bond attributes is deprecated")
    def __getitem__(self, prop): # -> Any:
        """Allow dict-style access to attributes for backwards compatibility."""
        ...
    
    @deprecated("Dictionary style access to Bond attributes is deprecated")
    def __setitem__(self, prop, val): # -> None:
        """Allow dict-style setting of attributes for backwards compatibility."""
        ...
    
    @deprecated("Dictionary style access to Bond attributes is deprecated")
    def __contains__(self, prop): # -> bool:
        """Allow dict-style checking of attributes for backwards compatibility."""
        ...
    
    @deprecated("Dictionary style access to Bond attributes is deprecated")
    def __delitem__(self, prop): # -> None:
        """Allow dict-style deletion of attributes for backwards compatibility."""
        ...
    
    def to_dict(self) -> dict[str, t.Any]:
        """Return a dictionary containing Bond data."""
        ...
    


class Compound:
    """Represents a standardized chemical structure record from PubChem.

    The PubChem Compound database contains standardized and deduplicated chemical
    structures derived from the Substance database. Each Compound is uniquely identified
    by a CID (Compound Identifier) and represents a unique chemical structure with
    calculated properties, descriptors, and associated experimental data.

    Examples:
        >>> compound = Compound.from_cid(2244)  # Aspirin
        >>> print(f"Formula: {compound.molecular_formula}")
        Formula: C9H8O4
        >>> print(f"IUPAC: {compound.iupac_name}")
        IUPAC: 2-acetyloxybenzoic acid
        >>> print(f"MW: {compound.molecular_weight}")
        MW: 180.16
    """
    def __init__(self, record: dict[str, t.Any]) -> None:
        """Initialize a Compound with a record dict from the PubChem PUG REST service.

        Args:
            record: Compound record returned by the PubChem PUG REST service.

        Note:
            Most users will not need to instantiate a Compound instance directly from a
            record. The :meth:`from_cid()` class method and the :func:`~get_compounds()`
            function offer more convenient ways to obtain Compound instances, as they
            also handle the retrieval of the record from PubChem.
        """
        ...
    
    @classmethod
    def from_cid(cls, cid: int, **kwargs: QueryParam) -> Compound:
        """Retrieve the Compound record for the specified CID.

        Args:
            cid: The PubChem Compound Identifier (CID) to retrieve.
            **kwargs: Additional parameters to pass to the request.

        Example:
            c = Compound.from_cid(6819)
        """
        ...
    
    @property
    def record(self) -> dict[str, t.Any]:
        """The full compound record returned by the PubChem PUG REST service."""
        ...
    
    @record.setter
    def record(self, record: dict[str, t.Any]) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    def to_dict(self, properties: list[str] | None = ...) -> dict[str, t.Any]:
        """Return a dict containing Compound property data.

        Optionally specify a list of the desired properties to include. If
        ``properties`` is not specified, all properties are included, with the following
        exceptions:

        :attr:`synonyms`, :attr:`aids` and :attr:`sids` are not included unless
        explicitly specified. This is because they each require an extra request to the
        PubChem API to retrieve.

        :attr:`canonical_smiles` and :attr:`isomeric_smiles` are not included by
        default, as they are deprecated and have been replaced by
        :attr:`connectivity_smiles` and :attr:`smiles` respectively.

        Args:
            properties: List of desired properties.

        Returns:
            Dictionary of compound data.
        """
        ...
    
    def to_series(self, properties: list[str] | None = ...) -> pd.Series:
        """Return a pandas :class:`~pandas.Series` containing Compound data.

        Optionally specify a list of the desired properties to include as columns. If
        ``properties`` is not specified, all properties are included, with the following
        exceptions:

        :attr:`synonyms`, :attr:`aids` and :attr:`sids` are not included unless
        explicitly specified. This is because they each require an extra request to the
        PubChem API to retrieve.

        :attr:`canonical_smiles` and :attr:`isomeric_smiles` are not included by
        default, as they are deprecated and have been replaced by
        :attr:`connectivity_smiles` and :attr:`smiles` respectively.

        Args:
            properties: List of desired properties.
        """
        ...
    
    @property
    def cid(self) -> int | None:
        """The PubChem Compound Identifier (CID).

        .. note::

            When searching using a SMILES or InChI query that is not present in the
            PubChem Compound database, an automatically generated record may be returned
            that contains properties that have been calculated on the fly. These records
            will not have a CID property.
        """
        ...
    
    @property
    def elements(self) -> list[str]:
        """List of element symbols for atoms in this Compound."""
        ...
    
    @property
    def atoms(self) -> list[Atom]:
        """List of :class:`Atoms <pubchempy.Atom>` in this Compound."""
        ...
    
    @property
    def bonds(self) -> list[Bond]:
        """List of :class:`Bonds <pubchempy.Bond>` in this Compound."""
        ...
    
    @memoized_property
    def synonyms(self) -> list[str] | None:
        """Ranked list of all the names associated with this Compound.

        Requires an extra request. Result is cached.
        """
        ...
    
    @memoized_property
    def sids(self) -> list[int] | None:
        """List of Substance Identifiers associated with this Compound.

        Requires an extra request. Result is cached.
        """
        ...
    
    @memoized_property
    def aids(self) -> list[int] | None:
        """List of Assay Identifiers associated with this Compound.

        Requires an extra request. Result is cached.
        """
        ...
    
    @property
    def coordinate_type(self) -> str | None:
        """Whether this Compound has 2D or 3D coordinates."""
        ...
    
    @property
    def charge(self) -> int:
        """Formal charge on this Compound."""
        ...
    
    @property
    def molecular_formula(self) -> str | None:
        """Molecular formula.

        The molecular formula represents the number of atoms of each element in a
        compound. It does not contain any information about connectivity or structure.
        """
        ...
    
    @property
    def molecular_weight(self) -> float | None:
        """Molecular weight in g/mol.

        The molecular weight is the sum of all atomic weights of the constituent
        atoms in a compound, measured in g/mol. In the absence of explicit isotope
        labelling, averaged natural abundance is assumed. If an atom bears an
        explicit isotope label, 100% isotopic purity is assumed at this location.
        """
        ...
    
    @property
    @deprecated("Use connectivity_smiles instead")
    def canonical_smiles(self) -> str | None:
        """Canonical SMILES, with no stereochemistry information (deprecated).

        .. deprecated:: 1.0.5
           :attr:`canonical_smiles` is deprecated, use :attr:`connectivity_smiles`
           instead.
        """
        ...
    
    @property
    @deprecated("Use smiles instead")
    def isomeric_smiles(self) -> str | None:
        """Isomeric SMILES.

        .. deprecated:: 1.0.5
           :attr:`isomeric_smiles` is deprecated, use :attr:`smiles` instead.
        """
        ...
    
    @property
    def connectivity_smiles(self) -> str | None:
        """Connectivity SMILES string.

        A canonical SMILES string that includes connectivity information only. It
        excludes stereochemical and isotopic information.

        Replaces the deprecated :attr:`canonical_smiles` property.
        """
        ...
    
    @property
    def smiles(self) -> str | None:
        """Absolute SMILES string (isomeric and canonical).

        A canonical SMILES string that includes both stereochemical and isotopic
        information. This provides the most complete linear representation of the
        molecular structure.

        Replaces the deprecated :attr:`isomeric_smiles` property.
        """
        ...
    
    @property
    def inchi(self) -> str | None:
        """Standard IUPAC International Chemical Identifier (InChI).

        The InChI provides a unique, standardized representation of molecular
        structure that is not dependent on the software used to generate it.
        It includes connectivity, stereochemistry, and isotopic information
        in a layered format. This standard version does not allow for user
        selectable options in dealing with stereochemistry and tautomer layers.
        """
        ...
    
    @property
    def inchikey(self) -> str | None:
        """Standard InChIKey.

        A hashed version of the full standard InChI, consisting of 27 characters
        divided into three blocks separated by hyphens. The InChIKey provides a
        fixed-length identifier that is more suitable for database indexing and
        web searches than the full InChI string.
        """
        ...
    
    @property
    def iupac_name(self) -> str | None:
        """Preferred IUPAC name.

        The chemical name systematically determined according to IUPAC
        (International Union of Pure and Applied Chemistry) nomenclature rules.
        This is the preferred systematic name among the available IUPAC naming
        styles (Allowed, CAS-like Style, Preferred, Systematic, Traditional).
        """
        ...
    
    @property
    def xlogp(self) -> float | None:
        """XLogP octanol-water partition coefficient.

        A computationally generated octanol-water partition coefficient that
        measures the hydrophilicity or hydrophobicity of a molecule. Higher
        values indicate more lipophilic (fat-soluble) compounds, while lower
        values indicate more hydrophilic (water-soluble) compounds.
        """
        ...
    
    @property
    def exact_mass(self) -> float | None:
        """Exact mass in Da (Daltons).

        The mass of the most likely isotopic composition for a single molecule,
        corresponding to the most intense ion/molecule peak in a mass spectrum.
        This differs from molecular weight in that it uses the exact masses of
        specific isotopes rather than averaged atomic weights.
        """
        ...
    
    @property
    def monoisotopic_mass(self) -> float | None:
        """Monoisotopic mass in Da (Daltons).

        The mass of a molecule calculated using the mass of the most abundant
        isotope of each element. This provides a single, well-defined mass value
        useful for high-resolution mass spectrometry applications.
        """
        ...
    
    @property
    def tpsa(self) -> float | None:
        """Topological Polar Surface Area (TPSA).

        The topological polar surface area computed using the algorithm described
        by Ertl et al. TPSA is a commonly used descriptor for predicting drug
        absorption, as it correlates well with passive molecular transport through
        membranes. Values are typically expressed in square Ångströms.
        """
        ...
    
    @property
    def complexity(self) -> float | None:
        """Molecular complexity rating.

        A measure of molecular complexity computed using the Bertz/Hendrickson/
        Ihlenfeldt formula. This descriptor quantifies the structural complexity
        of a molecule based on factors such as the number of atoms, bonds,
        rings, and branching patterns.
        """
        ...
    
    @property
    def h_bond_donor_count(self) -> int | None:
        """Number of hydrogen-bond donors in the structure.

        Counts functional groups that can donate hydrogen bonds, such as
        -OH, -NH, and -SH groups. This descriptor is important for predicting
        drug-like properties and molecular interactions.
        """
        ...
    
    @property
    def h_bond_acceptor_count(self) -> int | None:
        """Number of hydrogen-bond acceptors in the structure.

        Counts functional groups that can accept hydrogen bonds, such as
        oxygen and nitrogen atoms with lone pairs. This descriptor is important
        for predicting drug-like properties and molecular interactions.
        """
        ...
    
    @property
    def rotatable_bond_count(self) -> int | None:
        """Number of rotatable bonds.

        Counts single bonds that can freely rotate, excluding bonds in rings
        and terminal bonds to hydrogen or methyl groups.
        """
        ...
    
    @property
    def fingerprint(self) -> str | None:
        """Raw padded and hex-encoded structural fingerprint from PubChem.

        Returns the raw padded and hex-encoded fingerprint as returned by the PUG REST
        API. This is the underlying data used to generate the human-readable binary
        fingerprint via the ``cactvs_fingerprint`` property. Most users should use
        ``cactvs_fingerprint`` instead for substructure analysis and similarity
        calculations.

        The PubChem fingerprint data is 881 bits in length. Binary data is stored in one
        byte increments. This fingerprint is, therefore, 111 bytes in length (888 bits),
        which includes padding of seven bits at the end to complete the last byte. A
        four-byte prefix, containing the bit length of the fingerprint (881 bits),
        increases the stored PubChem fingerprint size to 115 bytes (920 bits). This is
        then hex-encoded, resulting in a 230-character string.

        More information at:
        ftp://ftp.ncbi.nlm.nih.gov/pubchem/specifications/pubchem_fingerprints.txt
        """
        ...
    
    @property
    def cactvs_fingerprint(self) -> str | None:
        """PubChem CACTVS structural fingerprint as 881-bit binary string.

        Returns a binary fingerprint string where each character is a bit representing
        the presence (1) or absence (0) of specific chemical substructures and features.
        The 881-bit fingerprint is organized into sections covering:

        - Section 1: Hierarchical element counts (1-115)
        - Section 2: Rings in a canonical ring set (116-163)
        - Section 3: Simple atom pairs (164-218)
        - Section 4: Simple atom nearest neighbors (219-242)
        - Section 5: Detailed atom neighborhoods (243-707)
        - Section 6: Simple SMARTS patterns (708-881)

        This fingerprint enables efficient substructure searching, similarity
        calculations, and chemical clustering.

        More information at:
        ftp://ftp.ncbi.nlm.nih.gov/pubchem/specifications/pubchem_fingerprints.txt
        """
        ...
    
    @property
    def heavy_atom_count(self) -> int | None:
        """Number of heavy atoms (non-hydrogen atoms).

        Counts all atoms in the molecule except hydrogen. This is a basic descriptor of
        molecular size and is used in various chemical calculations and molecular
        property predictions.
        """
        ...
    
    @property
    def isotope_atom_count(self) -> int | None:
        """Number of atoms with enriched isotopes.

        Counts atoms that are specified with non-standard isotopes (e.g., ²H, ¹³C). Most
        organic molecules have a value of 0 unless they are isotopically labeled for
        research or analytical purposes.
        """
        ...
    
    @property
    def atom_stereo_count(self) -> int | None:
        """Total number of atoms with tetrahedral (sp³) stereochemistry.

        Counts atoms that have tetrahedral stereochemistry. This includes both defined
        and undefined stereocenters in the molecule.
        """
        ...
    
    @property
    def defined_atom_stereo_count(self) -> int | None:
        """Number of atoms with defined tetrahedral (sp³) stereochemistry.

        Counts stereocenters where the absolute configuration is explicitly specified
        (e.g. R or S). This excludes stereocenters where the  configuration is unknown
        or unspecified.
        """
        ...
    
    @property
    def undefined_atom_stereo_count(self) -> int | None:
        """Number of atoms with undefined tetrahedral (sp³) stereochemistry.

        Counts stereocenters where the absolute configuration is not specified or is
        unknown. These represent potential stereocenters that could have either R or S
        configuration, but this is not explicitly defined.
        """
        ...
    
    @property
    def bond_stereo_count(self) -> int | None:
        """Bond stereocenter count."""
        ...
    
    @property
    def defined_bond_stereo_count(self) -> int | None:
        """Defined bond stereocenter count."""
        ...
    
    @property
    def undefined_bond_stereo_count(self) -> int | None:
        """Undefined bond stereocenter count."""
        ...
    
    @property
    def covalent_unit_count(self) -> int | None:
        """Covalently-bonded unit count."""
        ...
    
    @property
    def volume_3d(self) -> float | None:
        """Analytic volume of the first diverse conformer.

        The 3D molecular volume calculated for the default (first diverse) conformer.
        This descriptor provides information about the space occupied by the molecule in
        three dimensions.
        """
        ...
    
    @property
    def multipoles_3d(self) -> list[float] | None:
        ...
    
    @property
    def conformer_rmsd_3d(self) -> float | None:
        """Conformer sampling RMSD in Å.

        The root-mean-square deviation of atomic positions between different conformers
        in the conformer model. This measures the structural diversity of the generated
        conformer ensemble.
        """
        ...
    
    @property
    def effective_rotor_count_3d(self) -> int | None:
        """Number of effective rotors in the 3D structure.

        A count of rotatable bonds that significantly contribute to conformational
        flexibility. This is often less than the total rotatable bond count as it
        excludes rotors that have restricted rotation due to steric or electronic
        effects.
        """
        ...
    
    @property
    def pharmacophore_features_3d(self) -> list[str] | None:
        """3D pharmacophore features present in the molecule.

        A list of pharmacophore feature types identified in the 3D structure, such as
        hydrogen bond donors, acceptors, aromatic rings, and hydrophobic regions. These
        features are important for drug-target interactions.
        """
        ...
    
    @property
    def mmff94_partial_charges_3d(self) -> list[str] | None:
        ...
    
    @property
    def mmff94_energy_3d(self) -> float | None:
        ...
    
    @property
    def conformer_id_3d(self) -> str | None:
        ...
    
    @property
    def shape_selfoverlap_3d(self) -> float | None:
        ...
    
    @property
    def feature_selfoverlap_3d(self) -> float | None:
        ...
    
    @property
    def shape_fingerprint_3d(self) -> list[str] | None:
        ...
    


class Substance:
    """Represents a raw chemical record as originally deposited to PubChem.

    The PubChem Substance database contains chemical records in their original deposited
    form, before standardization or processing. As a result, it contains duplicates,
    mixtures, and some records that don't make chemical sense. This means that Substance
    records contain fewer calculated properties, however they do have additional
    information about the original source that deposited the record.

    During PubChem's standardization process, Substances are processed to create
    standardized Compound records. Multiple Substances may map to the same Compound
    if they represent the same unique chemical structure. Some Substances may not
    map to any Compound if they cannot be standardized.

    Examples:
        >>> substance = Substance.from_sid(12345)
        >>> print(f"Source: {substance.source_name}")
        Source: KEGG
        >>> print(f"Depositor ID: {substance.source_id}")
        Depositor ID: C10159
        >>> print(f"Standardized to CID: {substance.standardized_cid}")
        Standardized to CID: 169683
    """
    def __init__(self, record: dict[str, t.Any]) -> None:
        """Initialize a Substance with a record dict from the PubChem PUG REST service.

        Args:
            record: Substance record returned by the PubChem PUG REST service.

        Note:
            Most users will not need to instantiate a Substance instance directly from a
            record. The :meth:`from_sid()` class method and the
            :func:`~get_substances()` function offer more convenient ways to obtain
            Substance instances, as they also handle the retrieval of the record from
            PubChem.
        """
        ...
    
    @classmethod
    def from_sid(cls, sid: int, **kwargs: QueryParam) -> Substance:
        """Retrieve the Substance record for the specified SID.

        Args:
            sid: The PubChem Substance Identifier (SID).
            **kwargs: Additional parameters to pass to the request.

        Example:
            s = Substance.from_sid(12345)
        """
        ...
    
    @property
    def record(self) -> dict[str, t.Any]:
        """The full substance record returned by the PubChem PUG REST service."""
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    def to_dict(self, properties: list[str] | None = ...) -> dict[str, t.Any]:
        """Return a dict containing Substance property data.

        Optionally specify a list of the desired properties to include. If
        ``properties`` is not specified, all properties are included, with the following
        exceptions:

        :attr:`cids` and :attr:`aids` are not included unless explicitly specified. This
        is because they each require an extra request to the PubChem API to retrieve.

        Args:
            properties: List of desired properties.

        Returns:
            Dictionary of substance data.
        """
        ...
    
    def to_series(self, properties: list[str] | None = ...) -> pd.Series:
        """Return a pandas :class:`~pandas.Series` containing Substance data.

        Optionally specify a list of the desired properties to include as columns. If
        ``properties`` is not specified, all properties are included, with the following
        exceptions:

        :attr:`cids` and :attr:`aids` are not included unless explicitly specified. This
        is because they each require an extra request to the PubChem API to retrieve.

        Args:
            properties: List of desired properties.
        """
        ...
    
    @property
    def sid(self) -> int:
        """The PubChem Substance Idenfitier (SID)."""
        ...
    
    @property
    def synonyms(self) -> list[str] | None:
        """A ranked list of all the names associated with this Substance."""
        ...
    
    @property
    def source_name(self) -> str:
        """The name of the PubChem depositor that was the source of this Substance."""
        ...
    
    @property
    def source_id(self) -> str:
        """Unique ID for this Substance from the PubChem depositor source."""
        ...
    
    @property
    def standardized_cid(self) -> int | None:
        """The CID of the Compound that was standardized from this Substance.

        May not exist if this Substance was not standardizable.
        """
        ...
    
    @memoized_property
    def standardized_compound(self) -> Compound | None:
        """The :class:`~pubchempy.Compound` that was standardized from this Substance.

        Requires an extra request. Result is cached. May not exist if this Substance was
        not standardizable.
        """
        ...
    
    @property
    def deposited_compound(self) -> Compound | None:
        """A :class:`~pubchempy.Compound` derived from the unstandardized Substance.

        This :class:`~pubchempy.Compound` is produced from the unstandardized Substance
        record as deposited. It will not have a ``cid`` and will be missing most
        properties.
        """
        ...
    
    @memoized_property
    def cids(self) -> list[int]:
        """A list of all CIDs for Compounds that were standardized from this Substance.

        Requires an extra request. Result is cached.
        """
        ...
    
    @memoized_property
    def aids(self) -> list[int]:
        """A list of all AIDs for Assays associated with this Substance.

        Requires an extra request. Result is cached.
        """
        ...
    


class Assay:
    """Represents a biological assay record from the PubChem BioAssay database.

    The PubChem BioAssay database contains experimental data from biological screening
    and testing programs. Each assay record describes the experimental conditions,
    methodology, and results for testing chemical compounds against biological targets.

    BioAssay records include:

    - Assay protocol and experimental conditions
    - Target information (proteins, genes, pathways)
    - Activity outcome definitions and thresholds
    - Results data linking compounds to biological activities
    - Source information and literature references

    Assays are identified by their AID (Assay Identifier) and can be retrieved
    using the ``from_aid()`` class method. The assay data provides the experimental
    context for understanding compound bioactivity data stored in PubChem.
    """
    def __init__(self, record: dict[str, t.Any]) -> None:
        """Initialize an Assay with a record dict from the PubChem PUG REST service.

        Args:
            record: Assay record returned by the PubChem PUG REST service.

        Note:
            Most users will not need to instantiate an Assay instance directly from a
            record. The :meth:`from_aid()` class method and the :func:`~get_assays()`
            function offer more convenient ways to obtain Assay instances, as they
            also handle the retrieval of the record from PubChem.
        """
        ...
    
    @classmethod
    def from_aid(cls, aid: int, **kwargs: QueryParam) -> Assay:
        """Retrieve the Assay record for the specified AID.

        Args:
            aid: The PubChem Assay Identifier (AID).
            **kwargs: Additional parameters to pass to the request.

        Example:
            a = Assay.from_aid(1234)
        """
        ...
    
    @property
    def record(self) -> dict[str, t.Any]:
        """The full assay record returned by the PubChem PUG REST service."""
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    def to_dict(self, properties: list[str] | None = ...) -> dict[str, t.Any]:
        """Return a dict containing Assay property data.

        Optionally specify a list of the desired properties to include. If
        ``properties`` is not specified, all properties are included.

        Args:
            properties: List of desired properties.

        Returns:
            Dictionary of assay data.
        """
        ...
    
    @property
    def aid(self) -> int:
        """The PubChem Assay Idenfitier (AID)."""
        ...
    
    @property
    def name(self) -> str:
        """The short assay name, used for display purposes."""
        ...
    
    @property
    def description(self) -> str:
        """Description."""
        ...
    
    @property
    def project_category(self) -> ProjectCategory | None:
        """Category to distinguish projects funded through MLSCN, MLPCN or other.

        Possible values include mlscn, mlpcn, mlscn-ap, mlpcn-ap, literature-extracted,
        literature-author, literature-publisher, rnaigi.
        """
        ...
    
    @property
    def comments(self) -> list[str]:
        """Comments and additional information."""
        ...
    
    @property
    def results(self) -> list[dict[str, t.Any]]:
        """A list of dictionaries containing details of the results from this Assay."""
        ...
    
    @property
    def target(self) -> list[dict[str, t.Any]] | None:
        """A list of dictionaries containing details of the Assay targets."""
        ...
    
    @property
    def revision(self) -> int:
        """Revision identifier for textual description."""
        ...
    
    @property
    def aid_version(self) -> int:
        """Incremented when the original depositor updates the record."""
        ...
    


def compounds_to_frame(compounds: list[Compound] | Compound, properties: list[str] | None = ...) -> pd.DataFrame:
    """Create a :class:`~pandas.DataFrame` from a :class:`~pubchempy.Compound` list.

    Optionally specify the desired :class:`~pubchempy.Compound` properties to include as
    columns in the pandas DataFrame.
    """
    ...

def substances_to_frame(substances: list[Substance] | Substance, properties: list[str] | None = ...) -> pd.DataFrame:
    """Create a :class:`~pandas.DataFrame` from a :class:`~pubchempy.Substance` list.

    Optionally specify a list of the desired :class:`~pubchempy.Substance` properties to
    include as columns in the pandas DataFrame.
    """
    ...

class PubChemPyDeprecationWarning(Warning):
    """Warning category for deprecated features."""
    ...


class PubChemPyError(Exception):
    """Base class for all PubChemPy exceptions."""
    ...


class ResponseParseError(PubChemPyError):
    """PubChem response is uninterpretable."""
    ...


class PubChemHTTPError(PubChemPyError):
    """Generic error class to handle HTTP error codes."""
    def __init__(self, code: int, msg: str, details: list[str]) -> None:
        """Initialize with HTTP status code, message, and additional details.

        Args:
            code: HTTP status code.
            msg: Error message.
            details: Additional error details from PubChem API.
        """
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    


def create_http_error(e: HTTPError) -> PubChemHTTPError:
    """Create appropriate PubChem HTTP error subclass based on status code."""
    ...

class BadRequestError(PubChemHTTPError):
    """400: Request is improperly formed (e.g. syntax error in the URL or POST body)."""
    ...


class NotFoundError(PubChemHTTPError):
    """404: The input record was not found (e.g. invalid CID)."""
    ...


class MethodNotAllowedError(PubChemHTTPError):
    """405: Request not allowed (e.g. invalid MIME type in the HTTP Accept header)."""
    ...


class ServerError(PubChemHTTPError):
    """500: Some problem on the server side (e.g. a database server down)."""
    ...


class UnimplementedError(PubChemHTTPError):
    """501: The requested operation has not (yet) been implemented by the server."""
    ...


class ServerBusyError(PubChemHTTPError):
    """503: Too many requests or server is busy, retry later."""
    ...


class TimeoutError(PubChemHTTPError):
    """504: The request timed out, from server overload or too broad a request.

    See :ref:`Avoiding TimeoutError <avoiding_timeouterror>` for more information.
    """
    ...


if __name__ == "__main__":
    ...
